=== casmarmik/ProjectInRobotics/KUKA_robot/RSI/INTERNAT/KRCSETUP/KRC/ROBOTER/Config/System/Common/Schemes/RSI.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Mit XMLSpy v2009 (http://www.altova.com) von Baramundi (KUKA Roboter GmbH) bearbeitet -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="RSI">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Interface" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="MemSize" type="xs:unsignedInt" minOccurs="0"/>
							<xs:element name="StopOnSDBTaskSwitch" type="xs:boolean" minOccurs="0"/>
							<xs:element name="Timeout" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:unsignedShort">
										<xs:minInclusive value="1"/>
										<xs:maxInclusive value="90"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="ALog" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Enabled" type="xs:boolean" minOccurs="0"/>
							<xs:element name="MQueueSize" type="xs:unsignedInt" minOccurs="0"/>
							<xs:element name="FileSize" type="xs:unsignedInt" minOccurs="0"/>
							<xs:element name="LogLevel" type="xs:string"/>
							<xs:element name="ErrorHistory" type="xs:boolean" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="NetDependency" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="NetConfig" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== casmarmik/ProjectInRobotics/KUKA_robot/RSI/INTERNAT/KRCSETUP/KRC/ROBOTER/Config/User/Common/RSI.xml
<?xml version="1.0" encoding="UTF-8"?>
<RSI xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/Roboter/Config/System/Common/Schemes/RSI.xsd">
	<Interface>
		<MemSize>500000</MemSize>
	</Interface>
	<ALog>
	    <Enabled>false</Enabled>
		<MQueueSize>100</MQueueSize>
		<FileSize>100000</FileSize>
		<LogLevel>NoLogging</LogLevel>
		<ErrorHistory>true</ErrorHistory>
	</ALog>
	<NetDependency>
      <NetConfig>
      </NetConfig>
   </NetDependency>
</RSI>
