=== casmarmik/ProjectInRobotics/KUKA_robot/RSI/INTERNAT/KRCSETUP/KRC/ROBOTER/Config/System/Common/Schemes/RSIContext.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Mit XMLSpy v2009 (http://www.altova.com) von Guldner (KUKA Roboter GmbH) bearbeitet -->
<!--W3C Schema erstellt mit XMLSpy v2009 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="RSIObjects">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Template" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:attribute name="Name" use="required"/>
						<xs:attribute name="Type" use="required"/>
						<xs:attribute name="Version" use="required"/>
						<xs:attribute name="OptParam"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="ExternalRefs" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="File" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="Type" type="xs:string" default="Context"/>
									<xs:attribute name="Name" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element ref="RSIObject" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="RSIObject">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Inputs" minOccurs="0"/>
				<xs:element ref="Parameters" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="LibName" type="xs:string"/>
			<xs:attribute name="ObjTypeID" type="xs:unsignedInt" use="required"/>
			<xs:attribute name="ObjType" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1" fixed="false"/>
						<xs:maxLength value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="ObjID" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="2"/>
						<xs:maxLength value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Parameters">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Parameter" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Parameter">
		<xs:complexType>
			<xs:attribute name="ParamValue" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
						<xs:maxLength value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="ParamID" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:unsignedInt">
						<xs:minInclusive value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="Name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="2"/>
						<xs:maxLength value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="IsPublic" type="xs:boolean"/>
			<xs:attribute name="IsRuntime" type="xs:boolean"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Inputs">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Input" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Input">
		<xs:complexType>
			<xs:attribute name="OutObjID" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="2"/>
						<xs:maxLength value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="OutIdx" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:unsignedInt">
						<xs:minInclusive value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="InIdx" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:unsignedInt">
						<xs:minInclusive value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== casmarmik/ProjectInRobotics/KUKA_robot/RSI/DOC/Examples/CircleCorr/Config/RSI_CircleCorr.rsi.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<RSIObjects xsi:noNamespaceSchemaLocation="/Roboter/Config/System/Common/Schemes/RSIContext.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <RSIObject ObjType="POSACT" ObjTypeID="24" ObjID="POSACT1">
    <Parameters>
      <Parameter Name="Type" ParamID="1" ParamValue="0" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="POSCORR" ObjTypeID="27" ObjID="POSCORR1">
    <Inputs>
      <Input InIdx="2" OutObjID="DELAY1" OutIdx="1" />
      <Input InIdx="3" OutObjID="SOURCE1" OutIdx="1" />
    </Inputs>
    <Parameters>
      <Parameter Name="LowerLimX" ParamID="1" ParamValue="0" />
      <Parameter Name="LowerLimY" ParamID="2" ParamValue="-5.1" />
      <Parameter Name="LowerLimZ" ParamID="3" ParamValue="-5.1" />
      <Parameter Name="UpperLimX" ParamID="4" ParamValue="0" />
      <Parameter Name="UpperLimY" ParamID="5" ParamValue="5.1" />
      <Parameter Name="UpperLimZ" ParamID="6" ParamValue="5.1" />
      <Parameter Name="MaxRotAngle" ParamID="7" ParamValue="0" />
      <Parameter Name="RefCorrSys" ParamID="1" ParamValue="1" IsRuntime="false" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="POSCORRMON" ObjTypeID="81" ObjID="POSCORRMON1">
    <Parameters>
      <Parameter Name="MaxTrans" ParamID="1" ParamValue="6.0" />
      <Parameter Name="MaxRotAngle" ParamID="2" ParamValue="0" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="STOP" ObjTypeID="18" ObjID="STOP1">
    <Inputs>
      <Input InIdx="1" OutObjID="TIMER1" OutIdx="1" />
    </Inputs>
    <Parameters>
      <Parameter Name="Mode" ParamID="1" ParamValue="4" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="SOURCE" ObjTypeID="45" ObjID="SOURCE1">
    <Parameters>
      <Parameter Name="Type" ParamID="1" ParamValue="1" />
      <Parameter Name="Offset" ParamID="2" ParamValue="0" />
      <Parameter Name="Amplitude" ParamID="3" ParamValue="5.0" IsPublic="true" />
      <Parameter Name="Period" ParamID="4" ParamValue="10" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="DELAY" ObjTypeID="50" ObjID="DELAY1">
    <Inputs>
      <Input InIdx="1" OutObjID="SOURCE1" OutIdx="1" />
    </Inputs>
    <Parameters>
      <Parameter Name="DelayTime" ParamID="1" ParamValue="2.5" IsRuntime="false" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="TIMER" ObjTypeID="40" ObjID="TIMER1">
    <Parameters>
      <Parameter Name="Reset" ParamID="1" ParamValue="False" />
      <Parameter Name="Time" ParamID="2" ParamValue="22.5" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="MONITOR" ObjTypeID="55" ObjID="MONITOR1">
    <Inputs>
      <Input InIdx="1" OutObjID="POSACT1" OutIdx="2" />
      <Input InIdx="2" OutObjID="POSACT1" OutIdx="3" />
    </Inputs>
    <Parameters>
      <Parameter Name="Refresh" ParamID="1" ParamValue="1" />
      <Parameter Name="IP" ParamID="1" ParamValue="192.168.0.1" IsRuntime="false" />
      <Parameter Name="Channel" ParamID="2" ParamValue="1" IsRuntime="false" />
    </Parameters>
  </RSIObject>
</RSIObjects>

=== casmarmik/ProjectInRobotics/KUKA_robot/TEST_controlRobotFromPC/test3.rsi.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<RSIObjects xsi:noNamespaceSchemaLocation="/Roboter/Config/System/Common/Schemes/RSIContext.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <RSIObject ObjType="ETHERNET" ObjTypeID="64" ObjID="ETHERNET1">
    <Parameters>
      <Parameter Name="ConfigFile" ParamID="1" ParamValue="test3.xml" IsRuntime="false" />
      <Parameter Name="Timeout" ParamID="1" ParamValue="100" />
      <Parameter Name="Flag" ParamID="4" ParamValue="1" />
      <Parameter Name="Precision" ParamID="8" ParamValue="1" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="MAP2SEN_PREA" ObjTypeID="17" ObjID="MAP2SEN_PREA1">
    <Inputs>
      <Input InIdx="1" OutObjID="ETHERNET1" OutIdx="2" />
    </Inputs>
    <Parameters>
      <Parameter Name="Index" ParamID="1" ParamValue="1" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="MAP2SEN_PREA" ObjTypeID="17" ObjID="MAP2SEN_PREA2">
    <Inputs>
      <Input InIdx="1" OutObjID="ETHERNET1" OutIdx="3" />
    </Inputs>
    <Parameters>
      <Parameter Name="Index" ParamID="1" ParamValue="2" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="MAP2SEN_PREA" ObjTypeID="17" ObjID="MAP2SEN_PREA3">
    <Inputs>
      <Input InIdx="1" OutObjID="ETHERNET1" OutIdx="5" />
    </Inputs>
    <Parameters>
      <Parameter Name="Index" ParamID="1" ParamValue="4" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="MAP2SEN_PREA" ObjTypeID="17" ObjID="MAP2SEN_PREA4">
    <Inputs>
      <Input InIdx="1" OutObjID="ETHERNET1" OutIdx="4" />
    </Inputs>
    <Parameters>
      <Parameter Name="Index" ParamID="1" ParamValue="3" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="MAP2SEN_PREA" ObjTypeID="17" ObjID="MAP2SEN_PREA5">
    <Inputs>
      <Input InIdx="1" OutObjID="ETHERNET1" OutIdx="6" />
    </Inputs>
    <Parameters>
      <Parameter Name="Index" ParamID="1" ParamValue="5" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="MAP2SEN_PREA" ObjTypeID="17" ObjID="MAP2SEN_PREA6">
    <Inputs>
      <Input InIdx="1" OutObjID="ETHERNET1" OutIdx="7" />
    </Inputs>
    <Parameters>
      <Parameter Name="Index" ParamID="1" ParamValue="6" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="MAP2SEN_PINT" ObjTypeID="16" ObjID="MAP2SEN_PINT1">
    <Inputs>
      <Input InIdx="1" OutObjID="ETHERNET1" OutIdx="1" />
    </Inputs>
    <Parameters>
      <Parameter Name="Index" ParamID="1" ParamValue="1" />
    </Parameters>
  </RSIObject>
</RSIObjects>

=== casmarmik/ProjectInRobotics/KUKA_robot/RSI/DOC/Examples/Transformations/Config/RSI_SigTransformation.rsi.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<RSIObjects xsi:noNamespaceSchemaLocation="/Roboter/Config/System/Common/Schemes/RSIContext.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <RSIObject ObjType="TRAFO_USERFRAME" ObjTypeID="65" ObjID="TRAFO_USERFRAME1">
    <Inputs>
      <Input InIdx="1" OutObjID="SOURCE1" OutIdx="1" />
      <Input InIdx="2" OutObjID="SOURCE2" OutIdx="1" />
      <Input InIdx="3" OutObjID="SOURCE3" OutIdx="1" />
    </Inputs>
    <Parameters>
      <Parameter Name="Type" ParamID="1" ParamValue="0" />
      <Parameter Name="FraX" ParamID="2" ParamValue="80.0" />
      <Parameter Name="FraY" ParamID="3" ParamValue="0.0" />
      <Parameter Name="FraZ" ParamID="4" ParamValue="-100.0" />
      <Parameter Name="FraA" ParamID="5" ParamValue="0.0" />
      <Parameter Name="FraB" ParamID="6" ParamValue="0.0" />
      <Parameter Name="FraC" ParamID="7" ParamValue="90" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="SOURCE" ObjTypeID="45" ObjID="SOURCE1">
    <Parameters>
      <Parameter Name="Type" ParamID="1" ParamValue="0" />
      <Parameter Name="Offset" ParamID="2" ParamValue="300" />
      <Parameter Name="Amplitude" ParamID="3" ParamValue="1" />
      <Parameter Name="Period" ParamID="4" ParamValue="5" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="SOURCE" ObjTypeID="45" ObjID="SOURCE2">
    <Parameters>
      <Parameter Name="Type" ParamID="1" ParamValue="0" />
      <Parameter Name="Offset" ParamID="2" ParamValue="0" />
      <Parameter Name="Amplitude" ParamID="3" ParamValue="1" />
      <Parameter Name="Period" ParamID="4" ParamValue="5" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="SOURCE" ObjTypeID="45" ObjID="SOURCE3">
    <Parameters>
      <Parameter Name="Type" ParamID="1" ParamValue="0" />
      <Parameter Name="Offset" ParamID="2" ParamValue="-50" />
      <Parameter Name="Amplitude" ParamID="3" ParamValue="1" />
      <Parameter Name="Period" ParamID="4" ParamValue="5" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="TRAFO_USERFRAME" ObjTypeID="65" ObjID="TRAFO_USERFRAME2">
    <Inputs>
      <Input InIdx="1" OutObjID="SOURCE4" OutIdx="1" />
      <Input InIdx="2" OutObjID="SOURCE5" OutIdx="1" />
      <Input InIdx="3" OutObjID="SOURCE6" OutIdx="1" />
    </Inputs>
    <Parameters>
      <Parameter Name="Type" ParamID="1" ParamValue="2" />
      <Parameter Name="FraX" ParamID="2" ParamValue="80.0" />
      <Parameter Name="FraY" ParamID="3" ParamValue="0.0" />
      <Parameter Name="FraZ" ParamID="4" ParamValue="-100.0" />
      <Parameter Name="FraA" ParamID="5" ParamValue="0" />
      <Parameter Name="FraB" ParamID="6" ParamValue="0" />
      <Parameter Name="FraC" ParamID="7" ParamValue="90" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="SOURCE" ObjTypeID="45" ObjID="SOURCE4">
    <Parameters>
      <Parameter Name="Type" ParamID="1" ParamValue="0" />
      <Parameter Name="Offset" ParamID="2" ParamValue="90" />
      <Parameter Name="Amplitude" ParamID="3" ParamValue="1" />
      <Parameter Name="Period" ParamID="4" ParamValue="5" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="SOURCE" ObjTypeID="45" ObjID="SOURCE5">
    <Parameters>
      <Parameter Name="Type" ParamID="1" ParamValue="0" />
      <Parameter Name="Offset" ParamID="2" ParamValue="0" />
      <Parameter Name="Amplitude" ParamID="3" ParamValue="1" />
      <Parameter Name="Period" ParamID="4" ParamValue="5" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="SOURCE" ObjTypeID="45" ObjID="SOURCE6">
    <Parameters>
      <Parameter Name="Type" ParamID="1" ParamValue="0" />
      <Parameter Name="Offset" ParamID="2" ParamValue="90" />
      <Parameter Name="Amplitude" ParamID="3" ParamValue="1" />
      <Parameter Name="Period" ParamID="4" ParamValue="5" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="TRAFO_ROBFRAME" ObjTypeID="66" ObjID="TRAFO_ROBFRAME1">
    <Inputs>
      <Input InIdx="1" OutObjID="TRAFO_USERFRAME1" OutIdx="1" />
      <Input InIdx="2" OutObjID="TRAFO_USERFRAME1" OutIdx="2" />
      <Input InIdx="3" OutObjID="TRAFO_USERFRAME1" OutIdx="3" />
    </Inputs>
    <Parameters>
      <Parameter Name="Type" ParamID="1" ParamValue="0" />
      <Parameter Name="Source" ParamID="2" ParamValue="3" />
      <Parameter Name="Target" ParamID="3" ParamValue="1" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="TRAFO_ROBFRAME" ObjTypeID="66" ObjID="TRAFO_ROBFRAME2">
    <Inputs>
      <Input InIdx="1" OutObjID="TRAFO_USERFRAME2" OutIdx="1" />
      <Input InIdx="2" OutObjID="TRAFO_USERFRAME2" OutIdx="2" />
      <Input InIdx="3" OutObjID="TRAFO_USERFRAME2" OutIdx="3" />
    </Inputs>
    <Parameters>
      <Parameter Name="Type" ParamID="1" ParamValue="2" />
      <Parameter Name="Source" ParamID="2" ParamValue="3" />
      <Parameter Name="Target" ParamID="3" ParamValue="1" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="MONITOR" ObjTypeID="55" ObjID="MONITOR1">
    <Inputs>
      <Input InIdx="1" OutObjID="TRAFO_ROBFRAME1" OutIdx="1" />
      <Input InIdx="2" OutObjID="TRAFO_ROBFRAME1" OutIdx="2" />
      <Input InIdx="3" OutObjID="TRAFO_ROBFRAME1" OutIdx="3" />
      <Input InIdx="4" OutObjID="TRAFO_ROBFRAME2" OutIdx="1" />
      <Input InIdx="5" OutObjID="TRAFO_ROBFRAME2" OutIdx="2" />
      <Input InIdx="6" OutObjID="TRAFO_ROBFRAME2" OutIdx="3" />
    </Inputs>
    <Parameters>
      <Parameter Name="Refresh" ParamID="1" ParamValue="1" />
      <Parameter Name="IP" ParamID="1" ParamValue="192.168.0.1" IsRuntime="false" />
      <Parameter Name="Channel" ParamID="2" ParamValue="1" IsRuntime="false" />
    </Parameters>
  </RSIObject>
</RSIObjects>

=== casmarmik/ProjectInRobotics/KUKA_robot/TEST_RemotePathExecution/WithAxisCorr/test5.rsi.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<RSIObjects xsi:noNamespaceSchemaLocation="/Roboter/Config/System/Common/Schemes/RSIContext.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <RSIObject ObjType="ETHERNET" ObjTypeID="64" ObjID="ETHERNET1">
    <Inputs>
      <Input InIdx="1" OutObjID="DIGOUT1" OutIdx="1" />
      <Input InIdx="2" OutObjID="DIGOUT2" OutIdx="1" />
    </Inputs>
    <Parameters>
      <Parameter Name="ConfigFile" ParamID="1" ParamValue="test5.xml" IsRuntime="false" />
      <Parameter Name="Timeout" ParamID="1" ParamValue="100" />
      <Parameter Name="Flag" ParamID="4" ParamValue="1" />
      <Parameter Name="Precision" ParamID="8" ParamValue="9" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="AXISCORR" ObjTypeID="33" ObjID="AXISCORR1">
    <Inputs>
      <Input InIdx="1" OutObjID="ETHERNET1" OutIdx="12" />
      <Input InIdx="2" OutObjID="ETHERNET1" OutIdx="13" />
      <Input InIdx="3" OutObjID="ETHERNET1" OutIdx="14" />
      <Input InIdx="4" OutObjID="ETHERNET1" OutIdx="15" />
      <Input InIdx="5" OutObjID="ETHERNET1" OutIdx="16" />
      <Input InIdx="6" OutObjID="ETHERNET1" OutIdx="17" />
    </Inputs>
    <Parameters>
      <Parameter Name="LowerLimA1" ParamID="1" ParamValue="-1000" />
      <Parameter Name="LowerLimA2" ParamID="2" ParamValue="-1000" />
      <Parameter Name="LowerLimA3" ParamID="3" ParamValue="-1000" />
      <Parameter Name="LowerLimA4" ParamID="4" ParamValue="-1000" />
      <Parameter Name="LowerLimA5" ParamID="5" ParamValue="-1000" />
      <Parameter Name="LowerLimA6" ParamID="6" ParamValue="-1000" />
      <Parameter Name="UpperLimA1" ParamID="13" ParamValue="1000" />
      <Parameter Name="UpperLimA2" ParamID="14" ParamValue="1000" />
      <Parameter Name="UpperLimA3" ParamID="15" ParamValue="1000" />
      <Parameter Name="UpperLimA4" ParamID="16" ParamValue="1000" />
      <Parameter Name="UpperLimA5" ParamID="17" ParamValue="1000" />
      <Parameter Name="UpperLimA6" ParamID="18" ParamValue="1000" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="STOP" ObjTypeID="18" ObjID="STOP1">
    <Inputs>
      <Input InIdx="1" OutObjID="ETHERNET1" OutIdx="5" />
    </Inputs>
    <Parameters>
      <Parameter Name="Mode" ParamID="1" ParamValue="4" />
      <Parameter Name="Channel" ParamID="2" ParamValue="0" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="MAP2SEN_PINT" ObjTypeID="16" ObjID="MAP2SEN_PINT1">
    <Inputs>
      <Input InIdx="1" OutObjID="ETHERNET1" OutIdx="1" />
    </Inputs>
    <Parameters>
      <Parameter Name="Index" ParamID="1" ParamValue="1" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="MAP2SEN_PINT" ObjTypeID="16" ObjID="MAP2SEN_PINT2">
    <Inputs>
      <Input InIdx="1" OutObjID="ETHERNET1" OutIdx="2" />
    </Inputs>
    <Parameters>
      <Parameter Name="Index" ParamID="1" ParamValue="2" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="MAP2SEN_PINT" ObjTypeID="16" ObjID="MAP2SEN_PINT3">
    <Inputs>
      <Input InIdx="1" OutObjID="ETHERNET1" OutIdx="3" />
    </Inputs>
    <Parameters>
      <Parameter Name="Index" ParamID="1" ParamValue="3" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="MAP2SEN_PINT" ObjTypeID="16" ObjID="MAP2SEN_PINT4">
    <Inputs>
      <Input InIdx="1" OutObjID="ETHERNET1" OutIdx="4" />
    </Inputs>
    <Parameters>
      <Parameter Name="Index" ParamID="1" ParamValue="4" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="MAP2SEN_PREA" ObjTypeID="17" ObjID="MAP2SEN_PREA1">
    <Inputs>
      <Input InIdx="1" OutObjID="ETHERNET1" OutIdx="6" />
    </Inputs>
    <Parameters>
      <Parameter Name="Index" ParamID="1" ParamValue="1" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="MAP2SEN_PREA" ObjTypeID="17" ObjID="MAP2SEN_PREA2">
    <Inputs>
      <Input InIdx="1" OutObjID="ETHERNET1" OutIdx="7" />
    </Inputs>
    <Parameters>
      <Parameter Name="Index" ParamID="1" ParamValue="2" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="MAP2SEN_PREA" ObjTypeID="17" ObjID="MAP2SEN_PREA3">
    <Inputs>
      <Input InIdx="1" OutObjID="ETHERNET1" OutIdx="8" />
    </Inputs>
    <Parameters>
      <Parameter Name="Index" ParamID="1" ParamValue="3" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="MAP2SEN_PREA" ObjTypeID="17" ObjID="MAP2SEN_PREA4">
    <Inputs>
      <Input InIdx="1" OutObjID="ETHERNET1" OutIdx="9" />
    </Inputs>
    <Parameters>
      <Parameter Name="Index" ParamID="1" ParamValue="4" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="MAP2SEN_PREA" ObjTypeID="17" ObjID="MAP2SEN_PREA5">
    <Inputs>
      <Input InIdx="1" OutObjID="ETHERNET1" OutIdx="10" />
    </Inputs>
    <Parameters>
      <Parameter Name="Index" ParamID="1" ParamValue="5" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="MAP2SEN_PREA" ObjTypeID="17" ObjID="MAP2SEN_PREA6">
    <Inputs>
      <Input InIdx="1" OutObjID="ETHERNET1" OutIdx="11" />
    </Inputs>
    <Parameters>
      <Parameter Name="Index" ParamID="1" ParamValue="6" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="DIGOUT" ObjTypeID="43" ObjID="DIGOUT1">
    <Parameters>
      <Parameter Name="Index" ParamID="1" ParamValue="500" />
      <Parameter Name="DataSize" ParamID="2" ParamValue="0" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="DIGOUT" ObjTypeID="43" ObjID="DIGOUT2">
    <Parameters>
      <Parameter Name="Index" ParamID="1" ParamValue="400" />
      <Parameter Name="DataSize" ParamID="2" ParamValue="0" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="AXISCORRMON" ObjTypeID="82" ObjID="AXISCORRMON1">
    <Parameters>
      <Parameter Name="MaxA1" ParamID="1" ParamValue="1000" />
      <Parameter Name="MaxA2" ParamID="2" ParamValue="1000" />
      <Parameter Name="MaxA3" ParamID="3" ParamValue="1000" />
      <Parameter Name="MaxA4" ParamID="4" ParamValue="1000" />
      <Parameter Name="MaxA5" ParamID="5" ParamValue="1000" />
      <Parameter Name="MaxA6" ParamID="6" ParamValue="1000" />
      <Parameter Name="MaxE1" ParamID="7" ParamValue="6.0" />
      <Parameter Name="MaxE2" ParamID="8" ParamValue="6.0" />
      <Parameter Name="MaxE3" ParamID="9" ParamValue="6.0" />
      <Parameter Name="MaxE4" ParamID="10" ParamValue="6.0" />
      <Parameter Name="MaxE5" ParamID="11" ParamValue="6.0" />
      <Parameter Name="MaxE6" ParamID="12" ParamValue="6.0" />
    </Parameters>
  </RSIObject>
</RSIObjects>

=== casmarmik/ProjectInRobotics/KUKA_robot/RSI/DOC/Examples/DistanceCtrl/Config/RSI_DistanceCtrl.rsi.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<RSIObjects xsi:noNamespaceSchemaLocation="/Roboter/Config/System/Common/Schemes/RSIContext.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <RSIObject ObjType="ANIN" ObjTypeID="30" ObjID="ANIN1">
    <Parameters>
      <Parameter Name="Index" ParamID="1" ParamValue="1" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="P" ObjTypeID="28" ObjID="P1">
    <Inputs>
      <Input InIdx="1" OutObjID="ANIN1" OutIdx="1" />
    </Inputs>
    <Parameters>
      <Parameter Name="KR" ParamID="1" ParamValue="35" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="SUM" ObjTypeID="31" ObjID="SUM1">
    <Inputs>
      <Input InIdx="1" OutObjID="P1" OutIdx="1" />
    </Inputs>
    <Parameters>
      <Parameter Name="cVal" ParamID="1" ParamValue="65" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="SUM" ObjTypeID="31" ObjID="SUM2">
    <Inputs>
      <Input InIdx="1" OutObjID="SUM1" OutIdx="1" />
    </Inputs>
    <Parameters>
      <Parameter Name="cVal" ParamID="1" ParamValue="-50" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="POSCORR" ObjTypeID="27" ObjID="POSCORR1">
    <Inputs>
      <Input InIdx="3" OutObjID="P2" OutIdx="1" />
    </Inputs>
    <Parameters>
      <Parameter Name="LowerLimX" ParamID="1" ParamValue="-5" />
      <Parameter Name="LowerLimY" ParamID="2" ParamValue="-5" />
      <Parameter Name="LowerLimZ" ParamID="3" ParamValue="-20" />
      <Parameter Name="UpperLimX" ParamID="4" ParamValue="5" />
      <Parameter Name="UpperLimY" ParamID="5" ParamValue="5" />
      <Parameter Name="UpperLimZ" ParamID="6" ParamValue="20" />
      <Parameter Name="MaxRotAngle" ParamID="7" ParamValue="5" />
      <Parameter Name="RefCorrSys" ParamID="1" ParamValue="1" IsRuntime="false" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="P" ObjTypeID="28" ObjID="P2">
    <Inputs>
      <Input InIdx="1" OutObjID="SUM2" OutIdx="1" />
    </Inputs>
    <Parameters>
      <Parameter Name="KR" ParamID="1" ParamValue="0.001" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="EQUAL" ObjTypeID="7" ObjID="EQUAL1">
    <Inputs>
      <Input InIdx="1" OutObjID="ANIN1" OutIdx="1" />
    </Inputs>
    <Parameters>
      <Parameter Name="CompVal" ParamID="1" ParamValue="0.0" />
      <Parameter Name="Tolerance" ParamID="2" ParamValue="0.9" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="NOT" ObjTypeID="10" ObjID="NOT1">
    <Inputs>
      <Input InIdx="1" OutObjID="EQUAL1" OutIdx="1" />
    </Inputs>
  </RSIObject>
  <RSIObject ObjType="STOP" ObjTypeID="18" ObjID="STOP1">
    <Inputs>
      <Input InIdx="1" OutObjID="NOT1" OutIdx="1" />
    </Inputs>
    <Parameters>
      <Parameter Name="Mode" ParamID="1" ParamValue="1" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="GREATER" ObjTypeID="6" ObjID="GREATER1">
    <Inputs>
      <Input InIdx="1" OutObjID="POSCORR1" OutIdx="1" />
    </Inputs>
    <Parameters>
      <Parameter Name="CompVal" ParamID="1" ParamValue="1.0" />
      <Parameter Name="Hysteresis" ParamID="2" ParamValue="0.0" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="STOP" ObjTypeID="18" ObjID="STOP2">
    <Inputs>
      <Input InIdx="1" OutObjID="GREATER1" OutIdx="1" />
    </Inputs>
    <Parameters>
      <Parameter Name="Mode" ParamID="1" ParamValue="1" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="MONITOR" ObjTypeID="55" ObjID="MONITOR1">
    <Inputs>
      <Input InIdx="1" OutObjID="NOT1" OutIdx="1" />
      <Input InIdx="2" OutObjID="SUM1" OutIdx="1" />
      <Input InIdx="3" OutObjID="POSCORR1" OutIdx="4" />
      <Input InIdx="4" OutObjID="GREATER1" OutIdx="1" />
      <Input InIdx="5" OutObjID="POSACT1" OutIdx="2" />
      <Input InIdx="6" OutObjID="POSACT1" OutIdx="3" />
    </Inputs>
    <Parameters>
      <Parameter Name="Refresh" ParamID="1" ParamValue="1" />
      <Parameter Name="IP" ParamID="1" ParamValue="192.168.0.1" IsRuntime="false" />
      <Parameter Name="Channel" ParamID="2" ParamValue="1" IsRuntime="false" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="POSCORRMON" ObjTypeID="81" ObjID="POSCORRMON1">
    <Parameters>
      <Parameter Name="MaxTrans" ParamID="1" ParamValue="25.0" />
      <Parameter Name="MaxRotAngle" ParamID="2" ParamValue="6.0" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="POSACT" ObjTypeID="24" ObjID="POSACT1">
    <Parameters>
      <Parameter Name="Type" ParamID="1" ParamValue="0" />
    </Parameters>
  </RSIObject>
</RSIObjects>
