=== casmarmik/ProjectInRobotics/KUKA_robot/RSI/INTERNAT/KRCSETUP/KRC/ROBOTER/Config/System/Common/Schemes/RSIContext.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Mit XMLSpy v2009 (http://www.altova.com) von Guldner (KUKA Roboter GmbH) bearbeitet -->
<!--W3C Schema erstellt mit XMLSpy v2009 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="RSIObjects">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Template" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:attribute name="Name" use="required"/>
						<xs:attribute name="Type" use="required"/>
						<xs:attribute name="Version" use="required"/>
						<xs:attribute name="OptParam"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="ExternalRefs" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="File" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="Type" type="xs:string" default="Context"/>
									<xs:attribute name="Name" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element ref="RSIObject" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="RSIObject">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Inputs" minOccurs="0"/>
				<xs:element ref="Parameters" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="LibName" type="xs:string"/>
			<xs:attribute name="ObjTypeID" type="xs:unsignedInt" use="required"/>
			<xs:attribute name="ObjType" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1" fixed="false"/>
						<xs:maxLength value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="ObjID" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="2"/>
						<xs:maxLength value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Parameters">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Parameter" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Parameter">
		<xs:complexType>
			<xs:attribute name="ParamValue" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
						<xs:maxLength value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="ParamID" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:unsignedInt">
						<xs:minInclusive value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="Name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="2"/>
						<xs:maxLength value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="IsPublic" type="xs:boolean"/>
			<xs:attribute name="IsRuntime" type="xs:boolean"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Inputs">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Input" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Input">
		<xs:complexType>
			<xs:attribute name="OutObjID" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="2"/>
						<xs:maxLength value="255"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="OutIdx" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:unsignedInt">
						<xs:minInclusive value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="InIdx" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:unsignedInt">
						<xs:minInclusive value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== casmarmik/ProjectInRobotics/KUKA_robot/RSI/DOC/Examples/Ethernet/Config/RSI_Ethernet.rsi.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<RSIObjects xsi:noNamespaceSchemaLocation="/Roboter/Config/System/Common/Schemes/RSIContext.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <RSIObject ObjType="DIGIN" ObjTypeID="29" ObjID="DIGIN1">
    <Parameters>
      <Parameter Name="Index" ParamID="1" ParamValue="1" />
      <Parameter Name="DataSize" ParamID="2" ParamValue="2" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="DIGOUT" ObjTypeID="43" ObjID="DIGOUT1">
    <Parameters>
      <Parameter Name="Index" ParamID="1" ParamValue="1" />
      <Parameter Name="DataSize" ParamID="2" ParamValue="0" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="DIGOUT" ObjTypeID="43" ObjID="DIGOUT2">
    <Parameters>
      <Parameter Name="Index" ParamID="1" ParamValue="2" />
      <Parameter Name="DataSize" ParamID="2" ParamValue="0" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="DIGOUT" ObjTypeID="43" ObjID="DIGOUT3">
    <Parameters>
      <Parameter Name="Index" ParamID="1" ParamValue="3" />
      <Parameter Name="DataSize" ParamID="2" ParamValue="0" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="SOURCE" ObjTypeID="45" ObjID="SOURCE1">
    <Parameters>
      <Parameter Name="Type" ParamID="1" ParamValue="1" />
      <Parameter Name="Offset" ParamID="2" ParamValue="0" />
      <Parameter Name="Amplitude" ParamID="3" ParamValue="50" />
      <Parameter Name="Period" ParamID="4" ParamValue="5" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="POSCORR" ObjTypeID="27" ObjID="POSCORR1">
    <Inputs>
      <Input InIdx="1" OutObjID="ETHERNET1" OutIdx="1" />
      <Input InIdx="2" OutObjID="ETHERNET1" OutIdx="2" />
      <Input InIdx="3" OutObjID="ETHERNET1" OutIdx="3" />
      <Input InIdx="4" OutObjID="ETHERNET1" OutIdx="4" />
      <Input InIdx="5" OutObjID="ETHERNET1" OutIdx="5" />
      <Input InIdx="6" OutObjID="ETHERNET1" OutIdx="6" />
    </Inputs>
    <Parameters>
      <Parameter Name="LowerLimX" ParamID="1" ParamValue="-5" />
      <Parameter Name="LowerLimY" ParamID="2" ParamValue="-5" />
      <Parameter Name="LowerLimZ" ParamID="3" ParamValue="-5" />
      <Parameter Name="UpperLimX" ParamID="4" ParamValue="5" />
      <Parameter Name="UpperLimY" ParamID="5" ParamValue="5" />
      <Parameter Name="UpperLimZ" ParamID="6" ParamValue="5" />
      <Parameter Name="MaxRotAngle" ParamID="7" ParamValue="5" />
      <Parameter Name="RefCorrSys" ParamID="1" ParamValue="1" IsRuntime="false" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="MAP2DIGOUT" ObjTypeID="14" ObjID="MAP2DIGOUT1">
    <Inputs>
      <Input InIdx="1" OutObjID="ETHERNET1" OutIdx="8" />
    </Inputs>
    <Parameters>
      <Parameter Name="Index" ParamID="1" ParamValue="2" />
      <Parameter Name="DataSize" ParamID="2" ParamValue="2" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="MAP2SEN_PREA" ObjTypeID="17" ObjID="MAP2SEN_PREA1">
    <Inputs>
      <Input InIdx="1" OutObjID="ETHERNET1" OutIdx="1" />
    </Inputs>
    <Parameters>
      <Parameter Name="Index" ParamID="1" ParamValue="1" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="MAP2SEN_PREA" ObjTypeID="17" ObjID="MAP2SEN_PREA2">
    <Inputs>
      <Input InIdx="1" OutObjID="ETHERNET1" OutIdx="2" />
    </Inputs>
    <Parameters>
      <Parameter Name="Index" ParamID="1" ParamValue="2" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="MAP2SEN_PREA" ObjTypeID="17" ObjID="MAP2SEN_PREA3">
    <Inputs>
      <Input InIdx="1" OutObjID="ETHERNET1" OutIdx="3" />
    </Inputs>
    <Parameters>
      <Parameter Name="Index" ParamID="1" ParamValue="3" />
    </Parameters>
  </RSIObject>
  <RSIObject ObjType="ETHERNET" ObjTypeID="64" ObjID="ETHERNET1">
    <Inputs>
      <Input InIdx="1" OutObjID="DIGIN1" OutIdx="1" />
      <Input InIdx="2" OutObjID="DIGOUT1" OutIdx="1" />
      <Input InIdx="3" OutObjID="DIGOUT2" OutIdx="1" />
      <Input InIdx="4" OutObjID="DIGOUT3" OutIdx="1" />
      <Input InIdx="5" OutObjID="SOURCE1" OutIdx="1" />
    </Inputs>
    <Parameters>
      <Parameter Name="ConfigFile" ParamID="1" ParamValue="RSI_EthernetConfig.xml" IsRuntime="false" />
      <Parameter Name="Timeout" ParamID="1" ParamValue="100" />
      <Parameter Name="Flag" ParamID="4" ParamValue="1" />
      <Parameter Name="Precision" ParamID="8" ParamValue="1" />
    </Parameters>
  </RSIObject>
</RSIObjects>
